# Generated by Django 2.2.6 on 2019-10-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20191021_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
