# Generated by Django 2.2.6 on 2019-10-31 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_asset_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='bookings',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
