# Generated by Django 2.2.6 on 2019-10-21 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hour_start', models.IntegerField(default=0)),
                ('hour_end', models.IntegerField(default=24)),
                ('mon_available', models.BooleanField(default=True)),
                ('tue_available', models.BooleanField(default=True)),
                ('wed_available', models.BooleanField(default=True)),
                ('thu_available', models.BooleanField(default=True)),
                ('fri_available', models.BooleanField(default=True)),
                ('sat_available', models.BooleanField(default=True)),
                ('sun_available', models.BooleanField(default=True)),
                ('mon_bookings', models.TextField(default='')),
                ('tue_bookings', models.TextField(default='')),
                ('wed_bookings', models.TextField(default='')),
                ('thu_bookings', models.TextField(default='')),
                ('fri_bookings', models.TextField(default='')),
                ('sat_bookings', models.TextField(default='')),
                ('sun_bookings', models.TextField(default='')),
                ('book_start', models.IntegerField(default=0)),
                ('book_end', models.IntegerField(default=0)),
                ('bookings', models.TextField(default='')),
                ('choose_day', models.TextField(default='')),
                ('business_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.TextField(default='')),
                ('business_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Asset')),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('user_booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
