# Generated by Django 2.2.6 on 2019-10-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='business_owner',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_day',
            field=models.TextField(default=''),
        ),
    ]
